repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-yaml
    - id: check-toml
    - id: trailing-whitespace

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.5.1'
  hooks:
    - id: mypy
      args: []

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: "v0.0.291"
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
    - id: black

# - repo: https://github.com/pycqa/pydocstyle
#   rev: 6.3.0
#   hooks:
#   -   id: pydocstyle
