name: deploy

on: [push]

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.10" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
          cache: 'poetry'

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run Pre-commit
        run: poetry run pre-commit run --show-diff-on-failure --color=always --all-files

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run tests
        run: poetry run pytest