name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.10" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}
          # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Install build packages
        run: pip install --upgrade pip build wheel setuptools

      - name: Install editable package
        run: pip install -e ".[dev]"

      - name: Run Mypy
        run: mypy pkg_name tests

      - name: Run Ruff
        run: ruff pkg_name tests

      - name: Run tests
        run: python -m pytest -v